In [1]:
import pandas as pd
ain = pd.read_csv('resu.csv')
print(ain.shape)
ain.head()

(3434, 100)

,ra_1,dec_1,iauname,petro_theta,petro_th50,petro_th90,elpetro_absmag_r,sersic_nmgy_r,redshift,mag_r,...,wrong_size_warning,address_1,rank1_1,rank2_1,ra_2,dec_2,address_2,rank1_2,rank2_2,Separation
0,175.891498,21.672287,J114333.71+214011.3,11.761320,5.081815,12.596584,-21.246426,203.72523,0.099172,16.727388,...,False,175.89149808110213_21.67228737779398_0.262_grz...,29750,0,175.890586,21.669819,/data/GZ_Decals/nomerge/175.8905862789053_21.6...,205503,0,9.395503
1,176.146426,6.427386,J114435.46+062548.7,13.916864,6.035047,18.316315,-21.767908,458.95126,0.103689,15.845584,...,False,176.1464259029576_6.42738628465911_0.262_grz_....,269645,1,176.147779,6.430212,/data/GZ_Decals/nomerge/176.14777944132385_6.4...,139974,1,11.265522
2,216.732487,-2.558337,J142656.20-023324.1,21.376790,10.158915,31.909264,-22.527197,1887.89530,0.082288,14.310056,...,False,216.73248662726843_-2.558336707515353_0.262_gr...,212945,2,216.734203,-2.556704,/data/GZ_Decals/nomerge/216.73420321996912_-2....,266784,2,8.523640
3,249.264230,26.699189,J163703.40+264157.0,6.613727,3.444424,10.334829,-20.715216,1071.42580,0.058080,14.925095,...,False,249.26423000107675_26.699189190862203_0.262_gr...,426741,3,249.263232,26.699682,/data/GZ_Decals/merge/249.2632324703534_26.699...,1569,3,3.667396
4,229.360383,12.946229,J151725.87+125645.1,13.142800,5.932321,15.874659,-21.615564,1499.35360,0.061528,14.560240,...,False,229.36038312245492_12.946228665259735_0.262_gr...,96249,4,229.357805,12.945866,/data/GZ_Decals/nomerge/229.35780548542343_12....,310266,4,9.138988

In [6]:
import os
from astropy.io import fits

dir = '/data/GZ_Decals/MGS_out_DECaLS/'
train = open('train_t.txt', 'w')

for b in ain['address_1']:
    ss = dir + b
    try:
        name = ss + '\n'
        hdu = fits.open(ss)
        img = hdu[0].data
        if len(img)==3 and len(img[0])==256:
            hdu.close()
            train.write(name)
    except:
        continue

train.close()

In [7]:
import os
from astropy.io import fits

train = open('train_t1.txt', 'w')

for b in ain['address_2']:
    ss = b
    try:
        name = ss + '\n'
        hdu = fits.open(ss)
        img = hdu[0].data
        if len(img)==3 and len(img[0])==256:
            hdu.close()
            train.write(name)
    except:
        continue

train.close()

In [3]:
import os
from astropy.io import fits

dir = '/data/GZ_Decals/MGS_out_DECaLS/'
train = open('train_tal.txt', 'w')

for b in range(len(ain['address_2'])):
    ss = ain['address_2'][b]
    name = dir + ain['address_1'][b] + ' ' + ain['address_2'][b] + '\n'
    train.write(name)

train.close()